### ISSUE TITLE
Cannot read property of 'length' of undefined when updating from 0.0.5 to 0.1.1

### ISSUE THREAD

**Issue by paw-lu** [plotly/dash-cytoscape#61]
Hello, 

Love the library.

Had a app running perfectly on `0.0.5`. But when I updated to `0.1.1` I get

```
Cannot read property 'length' of undefined

(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read property 'length' of undefined

    at Function.value (webpack-internal:///./node_modules/react-cytoscapejs/dist/react-cytoscape.js:1:3406)

    at Cytoscape.render (webpack-internal:///./src/lib/components/Cytoscape.react.js:350:54)

    at ce (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:98:136)

    at qg (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:97:440)

    at hi (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:104:285)

    at Qg (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:144:293)

    at Rg (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:145:168)

    at Sc (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:158:109)

    at Z (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:156:492)

    at Kc (http://127.0.0.1:8050/hh-networks/_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=0.24.0&m=1559931493:155:69)
```

The app itself [may be found here](https://gist.github.com/pscosta5/a3c2a3443eddfaf68d5dbd7430c351be)

Downgrading back to `0.0.5` allows the app to run perfectly fine.

**Comment by pscosta5** [comment]
[I have simplified the example here](https://gist.github.com/pscosta5/716b71fb476343d8a4bce45ea8016659) and have found the root of the issue.

The app seems to have issue with leaving the `elements` parameter in `cyto.Cytoscape` as undefined. Before, on `0.0.5` this was fine, some process would then push data to `cyto.Cytoscape`, it would update and visualize the network.

Now on newer versions if I leave the `elements` parameter blank it will spit out the error above and refuse to update.

**Comment by invokermain** [comment]
adding `elements={}` fixes the issue for me as well. This behaviour is different from dash-core-components where it is common to define something like `dcc.Graph(id='errors', className='plotitem')` in your layout before populating values with callbacks. The lack of any Python error or warning is frustrating as well. Even the browser console only hints that the problem is something is not defined.
